spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate.ddl-auto: validate
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/spring_security_db?serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  flyway.baseline-on-migrate: true